feat: add block participants updates
Solvro/web-eventownik pull request #35
Opened 2024-12-03 17:11 UTC by dawidlinek

## Intro
The participant list in blocks did not refresh after a participant registered. After conducting an in-depth analysis, I discovered that participant data in blocks is not refreshed at all. This is a critical functionality since users need real-time updates to confirm whether someone else has already taken their place in real life.

## Changes
I've added all the prefetch parameters I could change. By default, places are refreshed every second using a pooling methodology. This also happens after the window focus changes, after reconnecting, and on mounting. This ensures a smooth experience.

## Future development
I also noticed that the whole event (meaning configuration I guess) is also refreshed every second. This produces quite a lot of requests and we should ask ourselves how we can optimize it.

2024-12-04 07:12 UTC, Rei-x commented
gpt driven opis pr'ki, grubo

2024-12-04 07:14 UTC, Rei-x requested changes

2024-12-04 07:14 UTC, Rei-x commented on src/pages/rejestracja/[participationSlug]/index.tsx
> +    refetchOnMount: true,
ale wiesz że to nic nie zmienia bo by default tak jest?

2025-01-11 11:51 UTC, dawidlinek commented
@Rei-x faktycznie to są domyślne wartości, zostawiłem tylko refetchInterval

2025-01-11 11:53 UTC, Rei-x approved these changes

2025-01-11 11:55 UTC, merged